services:
  - type: web
    name: vad-asbl
    env: node
    region: frankfurt
    plan: free
    branch: main
    buildCommand: npm install && npx prisma generate
    startCommand: npx prisma db push --accept-data-loss && node prisma/seed.js && node src/index.js
    healthcheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        value: "file:./vad.db"
      - key: JWT_SECRET
        generateValue: true
      - key: PUBLIC_BASE_URL
        value: "https://vad-asbl.onrender.com"
